/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.prbb.activeagent;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.LogRecord;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.WindowConstants;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import ru.prbb.activeagent.services.TaskChecker;
import ru.prbb.activeagent.services.SubscriptionChecker;

/**
 *
 * @author bryhljaev
 */
public class MainJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private final Logger logger = Logger.getLogger(getClass().getName());

    private final DefaultListModel<SubscriptionChecker> subscription = new DefaultListModel<>();
    private final DefaultListModel<TaskChecker> jobber = new DefaultListModel<>();
    private final PlainDocument resultDoc = new PlainDocument();

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanelNorth = new JPanel();
        JPanel jPanel1 = new JPanel();
        JPanel jPanel1n = new JPanel();
        JButton subscriptionAdd = new JButton();
        JButton subscriptionDel = new JButton();
        Box.Filler filler1 = new Box.Filler(new Dimension(10, 0), new Dimension(10, 0), new Dimension(10, 32767));
        JButton subscriptionStart = new JButton();
        JButton subscriptionStop = new JButton();
        JScrollPane jScrollPaneSubscription = new JScrollPane();
        subscriptionList = new JList();
        JPanel jPanel2 = new JPanel();
        JPanel jPanel2n = new JPanel();
        JButton jobberAdd = new JButton();
        JButton jobberDel = new JButton();
        Box.Filler filler2 = new Box.Filler(new Dimension(10, 0), new Dimension(10, 0), new Dimension(10, 32767));
        JButton jobberStart = new JButton();
        JButton jobberStop = new JButton();
        JScrollPane jScrollPaneJobber = new JScrollPane();
        jobberList = new JList();
        JPanel jPanelCenter = new JPanel();
        JPanel jPanel3n = new JPanel();
        JButton resultClean = new JButton();
        JScrollPane jScrollPane1 = new JScrollPane();
        result = new JEditorPane();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Агент Bloomberg");
        setMinimumSize(new Dimension(500, 300));
        setPreferredSize(new Dimension(700, 526));
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelNorth.setLayout(new BoxLayout(jPanelNorth, BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new BorderLayout());

        jPanel1n.setLayout(new FlowLayout(FlowLayout.LEADING));

        subscriptionAdd.setText("Добавить");
        subscriptionAdd.setEnabled(false);
        subscriptionAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                subscriptionAddActionPerformed(evt);
            }
        });
        jPanel1n.add(subscriptionAdd);

        subscriptionDel.setText("Убрать");
        subscriptionDel.setEnabled(false);
        subscriptionDel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                subscriptionDelActionPerformed(evt);
            }
        });
        jPanel1n.add(subscriptionDel);
        jPanel1n.add(filler1);

        subscriptionStart.setText("Старт");
        subscriptionStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                subscriptionStartActionPerformed(evt);
            }
        });
        jPanel1n.add(subscriptionStart);

        subscriptionStop.setText("Стоп");
        subscriptionStop.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                subscriptionStopActionPerformed(evt);
            }
        });
        jPanel1n.add(subscriptionStop);

        jPanel1.add(jPanel1n, BorderLayout.PAGE_START);

        subscriptionList.setModel(subscription);
        jScrollPaneSubscription.setViewportView(subscriptionList);

        jPanel1.add(jScrollPaneSubscription, BorderLayout.CENTER);

        jPanelNorth.add(jPanel1);

        jPanel2.setLayout(new BorderLayout());

        jPanel2n.setLayout(new FlowLayout(FlowLayout.LEADING));

        jobberAdd.setText("Добавить");
        jobberAdd.setEnabled(false);
        jobberAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jobberAddActionPerformed(evt);
            }
        });
        jPanel2n.add(jobberAdd);

        jobberDel.setText("Убрать");
        jobberDel.setEnabled(false);
        jobberDel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jobberDelActionPerformed(evt);
            }
        });
        jPanel2n.add(jobberDel);
        jPanel2n.add(filler2);

        jobberStart.setText("Старт");
        jobberStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jobberStartActionPerformed(evt);
            }
        });
        jPanel2n.add(jobberStart);

        jobberStop.setText("Стоп");
        jobberStop.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jobberStopActionPerformed(evt);
            }
        });
        jPanel2n.add(jobberStop);

        jPanel2.add(jPanel2n, BorderLayout.PAGE_START);

        jobberList.setModel(jobber);
        jScrollPaneJobber.setViewportView(jobberList);

        jPanel2.add(jScrollPaneJobber, BorderLayout.CENTER);

        jPanelNorth.add(jPanel2);

        getContentPane().add(jPanelNorth, BorderLayout.PAGE_START);

        jPanelCenter.setPreferredSize(new Dimension(500, 200));
        jPanelCenter.setLayout(new BorderLayout());

        jPanel3n.setLayout(new FlowLayout(FlowLayout.LEADING));

        resultClean.setText("Очистить");
        resultClean.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resultCleanActionPerformed(evt);
            }
        });
        jPanel3n.add(resultClean);

        jPanelCenter.add(jPanel3n, BorderLayout.PAGE_START);

        result.setEditable(false);
        result.setDocument(resultDoc
        );
        jScrollPane1.setViewportView(result);

        jPanelCenter.add(jScrollPane1, BorderLayout.CENTER);

        getContentPane().add(jPanelCenter, BorderLayout.CENTER);

        setSize(new Dimension(510, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Logger.getLogger("").addHandler(new Handler() {
            private int count = 0;

            {
                setFormatter(new SimpleFormatter());
            }

            @Override
            public void publish(LogRecord record) {
                try {
                    if (++count > 999) {
                        resultCleanActionPerformed(null);
                        count = 0;
                    }

                    String str = getFormatter().format(record);

                    resultDoc.insertString(resultDoc.getLength(), str + '\n', null);

                    result.setCaretPosition(resultDoc.getLength());
                } catch (BadLocationException ex) {
                    reportError("BadLocationException", ex, 0);
                }
            }

            @Override
            public void flush() {
            }

            @Override
            public void close() {
            }
        });

        try {
            subscription.addElement(new SubscriptionChecker("172.23.153.164:8080"));
            subscription.addElement(new SubscriptionChecker("172.16.15.36:10180"));
            subscription.addElement(new SubscriptionChecker("172.16.15.36:10190"));
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }

        try {
            String hostMy = "172.23.153.164:8080";
            jobber.addElement(new TaskChecker(hostMy, "/analytics"));
            jobber.addElement(new TaskChecker(hostMy, "/Jobber"));
            jobber.addElement(new TaskChecker(hostMy, "/middleoffice"));
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        try {
            String hostWork = "172.16.15.36:10180";
            jobber.addElement(new TaskChecker(hostWork, "/analytics"));
            jobber.addElement(new TaskChecker(hostWork, "/Jobber"));
            jobber.addElement(new TaskChecker(hostWork, "/middleoffice"));
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        try {
            String hostTest = "172.16.15.36:10190";
            jobber.addElement(new TaskChecker(hostTest, "/analytics"));
            jobber.addElement(new TaskChecker(hostTest, "/Jobber"));
            jobber.addElement(new TaskChecker(hostTest, "/middleoffice"));
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < subscription.getSize(); i++) {
            SubscriptionChecker item = subscription.get(i);
            //item.start();
        }

        for (int i = 0; i < jobber.getSize(); i++) {
            TaskChecker item = jobber.get(i);
            //item.start();
        }
    }//GEN-LAST:event_formWindowOpened

    private void subscriptionAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_subscriptionAddActionPerformed
        try {
            String host = "localhost";
            // TODO add your handling code here:
            subscription.addElement(new SubscriptionChecker(host));
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_subscriptionAddActionPerformed

    private void subscriptionDelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_subscriptionDelActionPerformed
        try {
            List<SubscriptionChecker> list = subscriptionList.getSelectedValuesList();
            for (SubscriptionChecker item : list) {
                item.stop();
                subscription.removeElement(item);
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_subscriptionDelActionPerformed

    private void subscriptionStartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_subscriptionStartActionPerformed
        try {
            if (subscriptionList.isSelectionEmpty()) {
                if (showYesNoDialog("Запустить все подписки?")) {
                    Enumeration<SubscriptionChecker> items = subscription.elements();
                    while (items.hasMoreElements()) {
                        SubscriptionChecker item = items.nextElement();
                        item.start();
                    }
                }
            } else {
                List<SubscriptionChecker> list = subscriptionList.getSelectedValuesList();
                for (SubscriptionChecker item : list) {
                    item.start();
                }
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        subscriptionList.clearSelection();
    }//GEN-LAST:event_subscriptionStartActionPerformed

    private void subscriptionStopActionPerformed(ActionEvent evt) {//GEN-FIRST:event_subscriptionStopActionPerformed
        try {
            if (subscriptionList.isSelectionEmpty()) {
                Enumeration<SubscriptionChecker> items = subscription.elements();
                while (items.hasMoreElements()) {
                    SubscriptionChecker item = items.nextElement();
                    item.stop();
                }
            } else {
                List<SubscriptionChecker> list = subscriptionList.getSelectedValuesList();
                for (SubscriptionChecker item : list) {
                    item.stop();
                }
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        subscriptionList.clearSelection();
    }//GEN-LAST:event_subscriptionStopActionPerformed

    private void jobberAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jobberAddActionPerformed
        try {
            String host = "localhost";
            String servlet = "";
            // TODO add your handling code here:
            jobber.addElement(new TaskChecker(host, servlet));
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jobberAddActionPerformed

    private void jobberDelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jobberDelActionPerformed
        try {
            List<TaskChecker> list = jobberList.getSelectedValuesList();
            for (TaskChecker item : list) {
                item.stop();
                jobber.removeElement(item);
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jobberDelActionPerformed

    private void jobberStartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jobberStartActionPerformed
        try {
            if (jobberList.isSelectionEmpty()) {
                if (showYesNoDialog("Запустить все Jobber?")) {
                    Enumeration<TaskChecker> items = jobber.elements();
                    while (items.hasMoreElements()) {
                        TaskChecker item = items.nextElement();
                        item.start();
                    }
                }
            } else {
                List<TaskChecker> list = jobberList.getSelectedValuesList();
                for (TaskChecker item : list) {
                    item.start();
                }
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        jobberList.clearSelection();
    }//GEN-LAST:event_jobberStartActionPerformed

    private void jobberStopActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jobberStopActionPerformed
        try {
            if (jobberList.isSelectionEmpty()) {
                Enumeration<TaskChecker> items = jobber.elements();
                while (items.hasMoreElements()) {
                    TaskChecker item = items.nextElement();
                    item.stop();
                }
            } else {
                List<TaskChecker> list = jobberList.getSelectedValuesList();
                for (TaskChecker item : list) {
                    item.stop();
                }
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        jobberList.clearSelection();
    }//GEN-LAST:event_jobberStopActionPerformed

    private void resultCleanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resultCleanActionPerformed
        try {
            resultDoc.remove(0, resultDoc.getLength());
        } catch (BadLocationException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resultCleanActionPerformed

    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (showYesNoDialog("Остановить Агента?")) {
            setDefaultCloseOperation(EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JList jobberList;
    private JEditorPane result;
    private JList subscriptionList;
    // End of variables declaration//GEN-END:variables

    private boolean showYesNoDialog(String message) {
        int r = JOptionPane.showOptionDialog(rootPane, message, getTitle(), JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        return (r == JOptionPane.YES_OPTION);
    }
}
