/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.prbb.activeagent;

import java.net.MalformedURLException;
import java.util.List;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultListModel;

/**
 *
 * @author bryhljaev
 */
public class MainJFrame extends javax.swing.JFrame {

    private final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(10);
    private final DefaultListModel<SubscriptionChecker> subscription = new DefaultListModel<>();

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subscriptionAdd = new javax.swing.JButton();
        subscriptionDel = new javax.swing.JButton();
        subscriptionStart = new javax.swing.JButton();
        subscriptionStop = new javax.swing.JButton();
        jScrollPaneSubscription = new javax.swing.JScrollPane();
        subscriptionList = new javax.swing.JList();
        jobberAdd = new javax.swing.JButton();
        jobberDel = new javax.swing.JButton();
        jScrollPaneJobber = new javax.swing.JScrollPane();
        jobberList = new javax.swing.JList();
        jScrollPaneResult = new javax.swing.JScrollPane();
        result = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Агент Bloomberg");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        subscriptionAdd.setText("Добавить");
        subscriptionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscriptionAddActionPerformed(evt);
            }
        });

        subscriptionDel.setText("Убрать");
        subscriptionDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscriptionDelActionPerformed(evt);
            }
        });

        subscriptionStart.setText("Старт");
        subscriptionStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscriptionStartActionPerformed(evt);
            }
        });

        subscriptionStop.setText("Стоп");
        subscriptionStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscriptionStopActionPerformed(evt);
            }
        });

        subscriptionList.setModel(subscription);
        jScrollPaneSubscription.setViewportView(subscriptionList);

        jobberAdd.setText("Добавить");

        jobberDel.setText("Убрать");

        jobberList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneJobber.setViewportView(jobberList);

        result.setEditable(false);
        jScrollPaneResult.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneSubscription)
                    .addComponent(jScrollPaneResult)
                    .addComponent(jScrollPaneJobber)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jobberAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jobberDel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subscriptionAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subscriptionDel)
                                .addGap(18, 18, 18)
                                .addComponent(subscriptionStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subscriptionStop)))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subscriptionAdd)
                    .addComponent(subscriptionDel)
                    .addComponent(subscriptionStart)
                    .addComponent(subscriptionStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobberAdd)
                    .addComponent(jobberDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneJobber, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneResult, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //executor.scheduleWithFixedDelay(command, initDelay, delay, TimeUnit.SECONDS);
        try {
            subscription.addElement(new SubscriptionChecker("172.23.153.164:8080"));
            subscription.addElement(new SubscriptionChecker("172.16.15.36:10180"));
            subscription.addElement(new SubscriptionChecker("172.16.15.36:10190"));
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void subscriptionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionAddActionPerformed
        try {
            String host = "localhost";
            // TODO add your handling code here:
            subscription.addElement(new SubscriptionChecker(host));
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_subscriptionAddActionPerformed

    private void subscriptionDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionDelActionPerformed
        List<SubscriptionChecker> list = subscriptionList.getSelectedValuesList();
        for (SubscriptionChecker item : list) {
            System.out.println(item);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_subscriptionDelActionPerformed

    private void subscriptionStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionStartActionPerformed
        if (subscriptionList.isSelectionEmpty()) {
            for (Object item : subscription.toArray()) {
                System.out.println(item);
            }
        } else {
            List list = subscriptionList.getSelectedValuesList();
            for (Object item : list) {
                System.out.println(item);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_subscriptionStartActionPerformed

    private void subscriptionStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionStopActionPerformed
        if (subscriptionList.isSelectionEmpty()) {
            for (Object item : subscription.toArray()) {
                System.out.println(item);
            }
        } else {
            List list = subscriptionList.getSelectedValuesList();
            for (Object item : list) {
                System.out.println(item);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_subscriptionStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneJobber;
    private javax.swing.JScrollPane jScrollPaneResult;
    private javax.swing.JScrollPane jScrollPaneSubscription;
    private javax.swing.JButton jobberAdd;
    private javax.swing.JButton jobberDel;
    private javax.swing.JList jobberList;
    private javax.swing.JEditorPane result;
    private javax.swing.JButton subscriptionAdd;
    private javax.swing.JButton subscriptionDel;
    private javax.swing.JList subscriptionList;
    private javax.swing.JButton subscriptionStart;
    private javax.swing.JButton subscriptionStop;
    // End of variables declaration//GEN-END:variables
}
